config/routes.rb
Mahjongg::Application.routes.draw do
  resources :game_titles

  resources :times_games

  resources :users
  
  root to: "game_titles#index"

  

end

app/models/game_title.rb
class GameTitle < ActiveRecord::Base
  has_many :times_games
end

app/models/times_game.rb
class TimesGame < ActiveRecord::Base
  belongs_to :game_title
  

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_titles_controller.rb
class GameTitlesController < ApplicationController
  before_action :set_game_title, only: [:show, :edit, :update, :destroy]

  # GET /game_titles
  # GET /game_titles.json
  def index
    @game_titles = GameTitle.all
    @times = TimesGame.all
    @users = User.all
  end

  # GET /game_titles/1
  # GET /game_titles/1.json
  def show
    @title_id = params[:id]
    @times = TimesGame.where("game_titles_id=#{params[:id]}")
    @times_new = TimesGame.new
    g = GameTitle.where("id= #{params[:id]}").first
    @user_id =  [g.user1,g.user2,g.user3,g.user4] - [nil]



    @users = []
     @user_id.each{ |id| @users <<  User.find(id)}
p @users
  end

  # GET /game_titles/new
  def new
    @game_title = GameTitle.new
    @users = User.find(:all)
  end

  # GET /game_titles/1/edit
  def edit
  end

  # POST /game_titles
  # POST /game_titles.json
  def create
    @game_title = GameTitle.new(
      title: params["game_title"]["title"],  
      default_point: params["game_title"]["default_point"],
      back_point: params["game_title"]["back_point"],
      user1: params["game_title"]["user1"], 
      user2: params["game_title"]["user2"], 
      user3:params["game_title"]["user3"], 
      user4: params["game_title"]["user4"]
    )




    respond_to do |format|
      if @game_title.save
        format.html { redirect_to @game_title, notice: 'Game title was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game_title }
      else
        format.html { render action: 'new' }
        format.json { render json: @game_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_titles/1
  # PATCH/PUT /game_titles/1.json
  def update
    respond_to do |format|
      if @game_title.update(game_title_params)
        format.html { redirect_to @game_title, notice: 'Game title was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_titles/1
  # DELETE /game_titles/1.json
  def destroy
    @game_title.destroy
    respond_to do |format|
      format.html { redirect_to game_titles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_title
      @game_title = GameTitle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_title_params
      params.require(:game_title).permit(:title)
    end
end

app/controllers/times_games_controller.rb
class TimesGamesController < ApplicationController
  before_action :set_times_game, only: [:show, :edit, :update, :destroy]

  # GET /times_games
  # GET /times_games.json
  def index
    @times_games = TimesGame.all
  end

  # GET /times_games/1
  # GET /times_games/1.json
  def show
  end

  # GET /times_games/new
  def new
    @times_game = TimesGame.new
  end

  # GET /times_games/1/edit
  def edit
  end

  # POST /times_games
  # POST /times_games.json
  def create
    @times_game = TimesGame.new(
      game_titles_id: params["times_game"]["title_id"],
      user1: params["times_game"]["user1"], 
      user2: params["times_game"]["user2"], 
      user3: params["times_game"]["user3"], 
      user4: params["times_game"]["user4"],
      sta: params["times_game"]["sta"]
    )



    respond_to do |format|
      if @times_game.save
        format.html { redirect_to :back}
      end
    end
  end

  # PATCH/PUT /times_games/1
  # PATCH/PUT /times_games/1.json
  def update
    respond_to do |format|
      if @times_game.update(times_game_params)
        format.html { redirect_to :back}
      end
    end
  end

  # DELETE /times_games/1
  # DELETE /times_games/1.json
  def destroy
    @times_game.destroy
    respond_to do |format|
        format.html { redirect_to :back}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_times_game
      @times_game = TimesGame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def times_game_params
      params.require(:times_game).permit(:point, :sta)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :it_parent)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_titles_helper.rb
module GameTitlesHelper
end

app/helpers/times_games_helper.rb
module TimesGamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/game_titles/_edit_form.html.erb
<%= form_for(@game_title) do |f| %>
  <% if @game_title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_title.errors.count, "error") %> prohibited this game_title from being saved:</h2>

      <ul>
      <% @game_title.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_titles/_form.html.erb
<%= form_for(@game_title) do |f| %>
  <% if @game_title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_title.errors.count, "error") %> prohibited this game_title from being saved:</h2>

      <ul>
      <% @game_title.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <label>基本点</label>
    <%= f.text_field :default_point %><br>
    <label>戻り点</label>
    <%= f.text_field :back_point %><br>
    <%= f.select(:user1, @users.map{|u| [ u.name, u.id]} , :include_blank => true ) %>
    <%= f.select(:user2, @users.map{|u| [ u.name, u.id]} ,:include_blank => true ) %>
    <%= f.select(:user3, @users.map{|u| [ u.name, u.id]} , :include_blank => true ) %>
    <%= f.select(:user4, @users.map{|u| [ u.name, u.id]} , :include_blank => true ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_titles/edit.html.erb
<h1>ゲームタイトル編集</h1>

<%= render 'edit_form' %>

<%= link_to 'ゲーム詳細', @game_title %> |
<%= link_to '戻る', game_titles_path %>

app/views/game_titles/index.html.erb
<h1>ゲーム一覧</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @game_titles.each do |game_title| %>
    <% user1_point = @times.where( "game_titles_id = #{game_title.id}").sum(:user1) == 0 ? "" : user4_point = @times.where( "game_titles_id = #{game_title.id}").sum(:user1) %>
    <% user2_point = @times.where( "game_titles_id = #{game_title.id}").sum(:user2) == 0 ? "" : user4_point = @times.where( "game_titles_id = #{game_title.id}").sum(:user2) %>
    <% user3_point = @times.where( "game_titles_id = #{game_title.id}").sum(:user3) == 0 ? "" : user4_point = @times.where( "game_titles_id = #{game_title.id}").sum(:user3) %>
    <% user4_point = @times.where( "game_titles_id = #{game_title.id}").sum(:user4) == 0 ? "" : user4_point = @times.where( "game_titles_id = #{game_title.id}").sum(:user4) %>
      <tr>
        <td><%= game_title.title %></td>
        <td><%= link_to '詳細', game_title %></td>
        <td><%= link_to 'タイトル編集', edit_game_title_path(game_title) %></td>
        <td><%= @users.find_by(id: game_title.user1).nil? ? "" : @users.find_by(id: game_title.user1).name %></td>
        <td><%= @users.find_by(id: game_title.user2).nil? ? "" : @users.find_by(id: game_title.user2).name %></td>
        <td><%= @users.find_by(id: game_title.user3).nil? ? "" : @users.find_by(id: game_title.user3).name %></td>
        <td><%= @users.find_by(id: game_title.user4).nil? ? "" : @users.find_by(id: game_title.user4).name %></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><%= user1_point %></td>
        <td><%= user2_point %></td>
        <td><%= user3_point %></td>
        <td><%= user4_point %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ユーザーの追加', 'users#index' %>
<%= link_to 'ゲーム追加', new_game_title_path %>

app/views/game_titles/new.html.erb
<h1>ゲーム追加</h1>

<%= render 'form' %>

<%= link_to '戻る', game_titles_path %>

app/views/game_titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game_title.title %><br>
    <label>基本点</label>
    <label class="default_point"><%= @game_title.default_point  %></label><br>
    <label>戻り点</label>
    <label class="back_point"><%= @game_title.back_point %></label><br>
</p>
<table class="point_table">
  <tbody>
    <tr>
      <td><label>名前</label></td>
      <% @users.each do |user| %>
        <td><%= user.name %></td>
      <% end %>
    </tr>

    <% @times.each do |times_game| %>
      <tr>
        <td><label></label></td>
        <td><label class="point"><%= times_game.user1 %></label></td>
        <td><label class="point"><%= times_game.user2 %></label></td>
        <td><label class="point"><%= times_game.user3 %></label></td>
        <td><label class="point"><%= times_game.user4 %></label></td>
        <td><%= times_game.sta %></td>
        <td><%= link_to 'Destroy', times_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
      <tr>
        <td><label>合計点数</label></td>
        <td><label class="user_totalpoint"></td>
        <td ><label class="user_totalpoint"></td>
        <td ><label class="user_totalpoint"></td>
        <td ><label class="user_totalpoint"></td>
        <td ><label class=""></td>
      </tr>
      <tr>
        <td><label>アガリ数/ロン数</label></td>
        <td ><label class="user_sta"></td>
        <td ><label class="user_sta"></td>
        <td ><label class="user_sta"></td>
        <td ><label class="user_sta"></td>
        <td ><label class=""></td>
      </tr>
    <%= form_for(@times_new) do |f| %>
      <tr>
        <td></td>
        <td><%= f.hidden_field  :title_id, :value => @title_id %><%= f.text_field :user1 %></td>
        <td><%= f.text_field :user2 %></td>
        <td><%= f.text_field :user3 %></td>
        <td><%= f.text_field :user4 %></td>
        <td><%= f.select( :sta, ["ツモ","ロン"] ,:include_blank => true )  %></td>
        <td>
          <div class="actions">
            <%= f.submit %>
          </div>
        </td>

      </tr>
      
    <% end %>
  </tbody>
</table>
<%= link_to '戻る', game_titles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mahjongg</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/times_games/_form.html.erb
<%= form_for(@times_game) do |f| %>
  <% if @times_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@times_game.errors.count, "error") %> prohibited this times_game from being saved:</h2>

      <ul>
      <% @times_game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :point %><br>
    <%= f.number_field :point %>
  </div>
  <div class="field">
    <%= f.label :sta %><br>
    <%= f.text_field :sta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/times_games/edit.html.erb
<h1>Editing times_game</h1>

<%= render 'form' %>

<%= link_to 'Show', @times_game %> |
<%= link_to 'Back', times_games_path %>

app/views/times_games/index.html.erb
<h1>Listing times_games</h1>

<table>
  <thead>
    <tr>
      <th>Point</th>
      <th>Sta</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @times_games.each do |times_game| %>
      <tr>
        <td><%= times_game.point %></td>
        <td><%= times_game.sta %></td>
        <td><%= link_to 'Show', times_game %></td>
        <td><%= link_to 'Edit', edit_times_game_path(times_game) %></td>
        <td><%= link_to 'Destroy', times_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Times game', new_times_game_path %>

app/views/times_games/new.html.erb
<h1>New times_game</h1>

<%= render 'form' %>

<%= link_to 'Back', times_games_path %>

app/views/times_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Point:</strong>
  <%= @times_game.point %>
</p>

<p>
  <strong>Sta:</strong>
  <%= @times_game.sta %>
</p>

<%= link_to 'Edit', edit_times_game_path(@times_game) %> |
<%= link_to 'Back', times_games_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :名前 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー編集</h1>

<%= render 'form' %>

<%= link_to 'ユーザー管理画面へ', @user %> |
<%= link_to '戻る', users_path %>

app/views/users/index.html.erb
<h1>ユーザー管理</h1>

<table>
  <thead>
    <tr>
      <td>名前</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to '編集', edit_user_path(user) %></td>
        <td><%= link_to '削除', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ユーザーの追加', new_user_path %>

<%= link_to 'ゲームの記録へ', 'game_titles#index' %>

app/views/users/new.html.erb
<h1>ユーザーの追加</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>It parent:</strong>
  <%= @user.it_parent %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>